#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path
import sys
import glob
from ase.io import read
from ase.io import write

args = sys.argv
step = int(args[1])
in_dir = args[2]
output = args[3]

files = glob.glob(path.join(in_dir, '*.xyz'))
for f in files:
    images = read(f, index='::{}'.format(step), format='xyz')
    write(output, images, format='xyz', append=True)
