#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import ase.io

args = sys.argv

# argv[0] contains all args
if len(args) is not 3 + 1:
    print(f"""
Error: args should have 3 but has {len(args)-1}

The format should be

$ vasp2xyz [PREFIX] [OUTCAR] [XYZFILE]\
""")
    sys.exit(1)

prefix = args[1]
input = args[2]
output = args[3]

images = []

for atoms in ase.io.iread(input, index=':', format='vasp-out'):
    # stress = atoms.get_stress(voigt=False)
    # atoms.set_param_value('stress', stress)
    atoms.info['tag'] = prefix + atoms.get_chemical_formula()
    images.append(atoms)

ase.io.write(output, images, format='xyz')
